//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirconType
    {
        public int AirconTypeID { get; set; }
        public string AirconTypeReference { get; set; }
        public string AirconTypeDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedByDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public bool Active { get; set; }
    }
}
