//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchMaster
    {
        public int BatchID { get; set; }
        public int BatchTypeID { get; set; }
        public string ReferenceNo { get; set; }
        public string BatchDescription { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<int> BatchCount { get; set; }
        public Nullable<decimal> BatchAmount { get; set; }
        public int EntityTypeID { get; set; }
        public int UserReference { get; set; }
        public int UserSubRef { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool Active { get; set; }
        public bool Assessed { get; set; }
        public Nullable<decimal> AssessedAmount { get; set; }
        public Nullable<int> AssessedBy { get; set; }
        public Nullable<System.DateTime> AssessedDate { get; set; }
        public string PaymentRef { get; set; }
        public byte[] PaymentFileByte { get; set; }
        public string PaymentFileType { get; set; }
        public Nullable<int> PaymentBy { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool Downloaded { get; set; }
        public Nullable<int> DownloadedBy { get; set; }
        public Nullable<System.DateTime> DownloadedDate { get; set; }
        public bool ForPickUp { get; set; }
        public Nullable<int> ForPickUpBy { get; set; }
        public Nullable<System.DateTime> ForPickUpDate { get; set; }
        public bool Rejected { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string RejectedRemarks { get; set; }
        public bool Received { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledRemarks { get; set; }
        public bool Reprocessed { get; set; }
        public Nullable<int> ReprocessedBy { get; set; }
        public Nullable<System.DateTime> ReprocessedDate { get; set; }
        public string ReprocessedRemarks { get; set; }
        public byte[] PaymentEPATFileByte { get; set; }
        public string PaymentEPATFileType { get; set; }
        public Nullable<int> LTOBranchID { get; set; }
    }
}
