//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDetails
    {
        public int BatchDetailID { get; set; }
        public int BatchID { get; set; }
        public int VehicleID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool Assessed { get; set; }
        public Nullable<decimal> AssessedAmount { get; set; }
        public Nullable<int> AssessedBy { get; set; }
        public Nullable<System.DateTime> AssessedDate { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool Rejected { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string RejectedRemarks { get; set; }
    }
}
