//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerInvoice
    {
        public int InvoiceID { get; set; }
        public int DealerBranchID { get; set; }
        public int CustomerID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public byte[] InvoiceByte { get; set; }
        public string COC { get; set; }
        public byte[] COCByte { get; set; }
        public string COCAuthenticationCode { get; set; }
        public int VehicleID { get; set; }
        public decimal VehicleCost { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string PreferredEndingPlateNumber { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public string InvoiceContentType { get; set; }
        public string COCContentType { get; set; }
        public string COCPolicyNumber { get; set; }
        public int VehicleTypeID { get; set; }
        public int VehicleClassificationID { get; set; }
        public int TaxTypeID { get; set; }
        public Nullable<System.DateTime> COCInceptionDate { get; set; }
        public Nullable<System.DateTime> COCExpirationDate { get; set; }
        public Nullable<decimal> COCPremium { get; set; }
        public string AffidavitOfConversion { get; set; }
        public string AffidavitOfConversionContentType { get; set; }
        public byte[] AffidavitOfConversionByte { get; set; }
        public bool Encumbered { get; set; }
        public string FinancialInstitution { get; set; }
        public bool AutoGenerateCOC { get; set; }
        public Nullable<decimal> COCTaxes { get; set; }
        public Nullable<decimal> COCAuthenticationFee { get; set; }
        public Nullable<decimal> COCBasicPremium { get; set; }
        public Nullable<decimal> COCVAT { get; set; }
        public Nullable<decimal> COCDST { get; set; }
        public Nullable<decimal> COCLGT { get; set; }
    }
}
