//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionEntryType
    {
        public int TransactionEntryTypeID { get; set; }
        public string TransactionEntryTypeName { get; set; }
        public decimal TransactionEntryMultiplier { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Updatedy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
