//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDealerVehicleMake
    {
        public int DealerVehicleMakeID { get; set; }
        public int DealerID { get; set; }
        public string DealerName { get; set; }
        public int VehicleMakeID { get; set; }
        public string VehicleMakeName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
    }
}
