//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDealerInvoice
    {
        public int InvoiceID { get; set; }
        public int DealerBranchID { get; set; }
        public int CustomerID { get; set; }
        public string InvoiceNumber { get; set; }
        public byte[] InvoiceByte { get; set; }
        public string COC { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int TitleID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string CorpName { get; set; }
        public string TitleName { get; set; }
        public string TitleAbbreviation { get; set; }
        public string DealerBranchName { get; set; }
        public int DealerID { get; set; }
        public string DealerName { get; set; }
        public byte[] COCByte { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public string InsuranceName { get; set; }
        public int VehicleID { get; set; }
    }
}
