//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProvinceCity
    {
        public int ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public int CityID { get; set; }
        public string CityName { get; set; }
        public string ProvinceNumber { get; set; }
        public string CityNumber { get; set; }
    }
}
