//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTransactionTypeList
    {
        public int TransactionTypeID { get; set; }
        public string TransactionName { get; set; }
        public bool Active { get; set; }
        public int TransactionEntryTypeID { get; set; }
        public string TransactionEntryTypeName { get; set; }
    }
}
