//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserList
    {
        public int UserID { get; set; }
        public int UserEntityID { get; set; }
        public int UserRoleID { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> SubReferenceID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool Active { get; set; }
        public string UserEntityName { get; set; }
        public string UserRoleName { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> LTOUserTypeID { get; set; }
    }
}
